// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://aujegmilkwsmwpzrfdaf.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1amVnbWlsa3dzbXdwenJmZGFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI5MTcwNTcsImV4cCI6MjA0ODQ5MzA1N30.hW7OU9a47GjMURDOK_DSjWUx6s9gOoJOosidOFYP6-M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);